version: "3"

services:
  db:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}-db
    volumes:
      - "db_app:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3338:3306
    networks:
      - symfony
  php:
    build:
      context: ./docker/php
      args:
        TIMEZONE: ${TIMEZONE}
    container_name: ${PROJECT_NAME}-php
    volumes:
      - ./app:/var/www/symfony/
      - ./app/var/cache:/var/www/symfony/app/var/cache
      - ./app/vendor:/var/www/symfony/app/vendor
    networks:
      - symfony
  nginx:
    build:
      context: ./docker/nginx
    container_name: ${PROJECT_NAME}-nginx
    volumes:
      - ./app:/var/www/symfony/
      - ./app/var/cache:/var/www/symfony/app/var/cache
      - ./app/vendor:/var/www/symfony/app/vendor

    ports:
      - 8081:80
    networks:
      - symfony
    env_file:
      - .env.nginx.local
#  ###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Закомментировать если используется ssl
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'konshensx'
      MERCURE_SUBSCRIBER_JWT_KEY: 'konshensx'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://127.0.0.1:8081 http://host.docker.internal:8081
    container_name: ${PROJECT_NAME}-mercure
    ports:
      - "9000:80"
      # - "9001:443"
    networks:
      - symfony
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    volumes:
      - mercure_data:/data
      - mercure_config:/config

####< symfony/mercure-bundle ###

volumes:
  db_app:
  mercure_data:
  mercure_config:

networks:
  symfony:
