version: "3"

services:
  db:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}-db
    volumes:
      - "db_app:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3338:3306
    networks:
      - symfony
  php:
    build:
      context: ./docker/php
      args:
        TIMEZONE: ${TIMEZONE}
    container_name: ${PROJECT_NAME}-php
    volumes:
      - ./app:/var/www/symfony/
    networks:
      - symfony
  nginx:
    build:
      context: ./docker/nginx
    container_name: ${PROJECT_NAME}-nginx
    volumes:
      - ./app:/var/www/symfony/
    ports:
      - 8081:80
    networks:
      - symfony
    env_file:
      - .env.nginx.local

volumes:
  db_app:

networks:
  symfony:
